Knn Algo

In [1]:
!pip3 install numpy
!pip3 install pandas
!pip3 install matplotlib
!pip3 install  scikit-learn

Requirement already satisfied: numpy in /home/sudip/.local/lib/python3.8/site-packages (1.23.4)
Requirement already satisfied: pandas in /home/sudip/.local/lib/python3.8/site-packages (1.5.1)
Requirement already satisfied: pytz>=2020.1 in /home/sudip/.local/lib/python3.8/site-packages (from pandas) (2022.6)
Requirement already satisfied: python-dateutil>=2.8.1 in /home/sudip/.local/lib/python3.8/site-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /home/sudip/.local/lib/python3.8/site-packages (from pandas) (1.23.4)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.1->pandas) (1.14.0)
Collecting matplotlib
  Downloading matplotlib-3.6.3-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (9.4 MB)
     |████████████████████████████████| 9.4 MB 643 kB/s eta 0:00:01     |█████████████████████████       | 7.3 MB 540 kB/s eta 0:00:04
Requirement already satisfied: pyparsing>=2.2.1 in /home/sudip/.local/lib/python3.8/site-packages (from matplotlib) (3.0.9)
Collecting contourpy>=1.0.1
  Downloading contourpy-1.0.7-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (300 kB)
     |████████████████████████████████| 300 kB 2.2 MB/s eta 0:00:01
Collecting fonttools>=4.22.0
  Downloading fonttools-4.38.0-py3-none-any.whl (965 kB)
     |████████████████████████████████| 965 kB 723 kB/s eta 0:00:01
Requirement already satisfied: packaging>=20.0 in /home/sudip/.local/lib/python3.8/site-packages (from matplotlib) (21.3)
Requirement already satisfied: python-dateutil>=2.7 in /home/sudip/.local/lib/python3.8/site-packages (from matplotlib) (2.8.2)
Collecting cycler>=0.10
  Downloading cycler-0.11.0-py3-none-any.whl (6.4 kB)
Requirement already satisfied: pillow>=6.2.0 in /usr/lib/python3/dist-packages (from matplotlib) (7.0.0)
Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.4.4-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.2 MB)
     |████████████████████████████████| 1.2 MB 1.1 MB/s eta 0:00:01
Requirement already satisfied: numpy>=1.19 in /home/sudip/.local/lib/python3.8/site-packages (from matplotlib) (1.23.4)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.7->matplotlib) (1.14.0)
Installing collected packages: contourpy, fonttools, cycler, kiwisolver, matplotlib
Successfully installed contourpy-1.0.7 cycler-0.11.0 fonttools-4.38.0 kiwisolver-1.4.4 matplotlib-3.6.3
Requirement already satisfied: scikit-learn in /home/sudip/.local/lib/python3.8/site-packages (1.1.3)
Requirement already satisfied: numpy>=1.17.3 in /home/sudip/.local/lib/python3.8/site-packages (from scikit-learn) (1.23.4)
Requirement already satisfied: joblib>=1.0.0 in /home/sudip/.local/lib/python3.8/site-packages (from scikit-learn) (1.2.0)
Requirement already satisfied: scipy>=1.3.2 in /home/sudip/.local/lib/python3.8/site-packages (from scikit-learn) (1.9.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/sudip/.local/lib/python3.8/site-packages (from scikit-learn) (3.1.0)

In [2]:
import numpy as np
import pandas as pd

In [3]:
datasate=pd.read_csv('diabetes.csv')

In [7]:
datasate

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [11]:
datasate.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
from sklearn.preprocessing import StandardScaler

In [15]:
from sklearn.neighbors import KNeighborsClassifier

In [16]:
print(len(datasate))

768

In [17]:
# zero replece
zero=['Glucose', 'BloodPressure' ,'SkinThickness' ,'Insulin' ,'BMI']

In [19]:
for column in zero:
    datasate[column]=datasate[column].replace(0,np.NaN)
    mean=int(datasate[column].mean(skipna=True))
    datasate[column]=datasate[column].replace(np.NaN,mean)

In [20]:
datasate

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148.0,72.0,35.0,155.0,33.6,0.627,50,1
1,1,85.0,66.0,29.0,155.0,26.6,0.351,31,0
2,8,183.0,64.0,29.0,155.0,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101.0,76.0,48.0,180.0,32.9,0.171,63,0
764,2,122.0,70.0,27.0,155.0,36.8,0.340,27,0
765,5,121.0,72.0,23.0,112.0,26.2,0.245,30,0
766,1,126.0,60.0,29.0,155.0,30.1,0.349,47,1
767,1,93.0,70.0,31.0,155.0,30.4,0.315,23,0

In [21]:
print(datasate['Glucose'])

0      148.0
1       85.0
2      183.0
3       89.0
4      137.0
       ...
763    101.0
764    122.0
765    121.0
766    126.0
767     93.0
Name: Glucose, Length: 768, dtype: float64

In [22]:
x=datasate.iloc[:,0:8]
y=datasate.iloc[:,8]
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=0,test_size=0.2)

In [23]:
print(x)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6    148.0           72.0           35.0    155.0  33.6
1              1     85.0           66.0           29.0    155.0  26.6
2              8    183.0           64.0           29.0    155.0  23.3
3              1     89.0           66.0           23.0     94.0  28.1
4              0    137.0           40.0           35.0    168.0  43.1
..           ...      ...            ...            ...      ...   ...
763           10    101.0           76.0           48.0    180.0  32.9
764            2    122.0           70.0           27.0    155.0  36.8
765            5    121.0           72.0           23.0    112.0  26.2
766            1    126.0           60.0           29.0    155.0  30.1
767            1     93.0           70.0           31.0    155.0  30.4

     DiabetesPedigreeFunction  Age
0                       0.627   50
1                       0.351   31
2                       0.672   32
3                       0.167   21
4                       2.288   33
..                        ...  ...
763                     0.171   63
764                     0.340   27
765                     0.245   30
766                     0.349   47
767                     0.315   23

[768 rows x 8 columns]

In [24]:
sc_x=StandardScaler()
x_train=sc_x.fit_transform(x_train)
x_test=sc_x.transform(x_test)

In [25]:
x_test

array([[-0.8354355 ,  2.55686374,  0.28101426, ...,  1.47037408,
         2.78594417, -0.96569189],
       [-0.54480808, -0.4856059 ,  0.11438678, ...,  0.13970383,
        -0.1876381 , -0.88240283],
       [ 0.03644676, -1.51078589, -0.8853781 , ...,  0.19693696,
        -0.22668514, -0.71582471],
       ...,
       [ 0.03644676,  0.67185537,  1.11415166, ...,  1.62776519,
         0.53623395, -0.96569189],
       [-0.25418066, -0.187973  ,  0.11438678, ..., -0.90480077,
        -1.07971278, -0.79911377],
       [-0.8354355 , -0.4856059 , -0.0522407 , ..., -0.26092807,
         1.06487079, -0.79911377]])

In [ ]:
clissifire=KNeighborsClassifier(n_neighbors=11)

In [ ]:
# cm=confusion_matrix(y_test,y_pred)
# print(cm)
# print(f1_score(y_test,y_pred))
clissifire.fit(x)